#!/bin/sh
#
# wmrc config - global variables for wmrc
# (c) arcetera 2015 - wtfpl
#

# required (you probably don't want to change these)

WID=$(pfw)
WW=$(wattr w $WID)
WH=$(wattr h $WID)
CUR=${2:-$(pfw)}
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)
BWIDTH=$(wattr b $CUR)
PFW=$(pfw)

# files used for storing things like window geometry, etc (be VERY careful with these)

FSFILE=${FSFILE:-~/.fwin}                ## stores window geometry for fullscreen
GRPROOT=/tmp/groups                      ## where groups are stored
STATE_FILE=${STATE_FILE:-~/.dytyl_state} ## stores the current layout

# groups

GRPNUM=4 ## number of groups

# blur

WALL=~/.wall.jpg ## wallpaper to blur, should be the same as the currently set wallpaper
BLUR=2           ## blur radius. move up for more intense blur, move down for less intense blur.

# tiling

PANEL=${PANEL:-20} ## leaves space for the bar/panel
GAP=${GAP:-15}    ## how large the gaps should be

# borders

BW=${BW:-1}                    ## border width
ACTIVE=${ACTIVE:-0x88C0D0}     ## border color of active window
INACTIVE=${INACTIVE:-0x2E3440} ## border color of inactive window
